// This file is autogenerated when running rake app:run

import Appsignal from "@appsignal/javascript";

exports.appsignal = new Appsignal({
  key: "FRONT-END-KEY",
  revision: "abc123",
  uri: "https://appsignal-endpoint.net/collect"
});
